name: flutter_workshop_ui_project
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.2.1 # ใช้ Fonts จาก fonts.Google.com ได้ใน Project 
  font_awesome_flutter: ^11.0.0 # ใช้ Icon จาก fontawesome.com ได้ใน Project

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4 # ใช้สร้างไอคอนของ App ที่จะแสดงที่หน้า Home Screen 

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 

flutter:
  uses-material-design: true
  assets:
    - assets/images/